# ----- Example ----- #
# <Parameter>:
  # type: float
  # value: 
    # low: <float value>
    # high: <float value>
# <Parameter>:
  # type: log_float
  # value: 
    # low: <float value>
    # high: <float value>
# <Parameter>:
  # type: int
  # value: 
    # low: <int value>
    # high: <int value>
# <Parameter>:
  # type: list
  # value: 
    # - <value>
    # - <value>
    # - ...

EPS_START: # epsilon starting value
  type: list
  value:
    - 0.9
EPS_END: # endvalue of epsilon
  type: list
  value:
    - 0.01
EPS_DECAY: # steps until epsilon endvalue is reached
  type: int
  value:
    low: 100
    high: 10000
TAU: # soft-update rate
  type: float
  value:
    high: !!float 1e-1
    low: !!float 1e-7
GAMMA: # discount factor
  type: list
  value:
    - 0.99
LR: # learning rate
  type: float
  value:
    high: !!float 1e-1
    low: !!float 1e-7
CAPACITY: # capacity of replay memory
  type: int
  value:
    low: 1000
    high: 100000
MINI_BATCH_SIZE: # batch size of replay samples
  type: list
  value:
    - 32
    - 64
    - 128
    - 264
    - 528