EPS_START: 0.9 # epsilon starting value
EPS_END: 0.01 # endvalue of epsilon
EPS_DECAY: 100 # episods until epsilon endvalue is reached
TAU: 0.005 # soft-update rate
GAMMA: 0.99 # discount factor
LR: !!float 0.0003 # learning rate
CAPACITY: 400000 # capacity of replay memory
MINI_BATCH_SIZE: 32 # batch size of replay samples
# PER
ALPHA: 0.6
BETA: 0.4