# Architecture
DOUBLE_DQN: !!bool false
PER: !!bool false
DUELING: !!bool true
NOISY: !!bool false
# Hyperparameters
EPS_START: 0.9 # epsilon starting value
EPS_END: 0.01 # endvalue of epsilon
EPS_DECAY: 600 # episods until epsilon endvalue is reached
TAU: 0.0027 # soft-update rate
GAMMA: 0.99 # discount factor
LR: !!float 0.00076 # learning rate
CAPACITY: 10000 # capacity of replay memory
MINI_BATCH_SIZE: 32 # batch size of replay samples
# PER
ALPHA: 0.23
BETA: 0.33